baseURL = 'http://rsk3d.com'
languageCode = 'en-us'
title = 'RSK3D'
theme = 'PaperMod'

[params]
  homeInfoParams = { Title = "Hi, I'm RSK3D 👋", Content = "3D Designer • Developer • Tech Enthusiast" }
  ShowReadingTime = false
  ShowBreadCrumbs = false
  ShowPostNavLinks = false
  ShowCodeCopyButtons = true
  defaultTheme = "dark"

[[params.socialIcons]]
  name = "github"
  url = ""

[[params.socialIcons]]
  name = "linkedin"
  url = ""

[[params.socialIcons]]
  name = "email"
  url = ""
